services:
  skillz:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        FIKA_VERSION: v2.4.8
        SPT_VERSION: 3.11.3
        SKILLSET_BRANCH: 3.11
    ports:
      - '6969:6969'
