"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.defaultEscapeTimes = exports.mainBossNameList = exports.bossesToRemoveFromPool = exports.originalMapList = exports.configLocations = exports.defaultHostility = void 0;
exports.defaultHostility = [
    {
        AlwaysEnemies: [
            "bossTest",
            "followerTest",
            "bossKilla",
            "bossKojaniy",
            "followerKojaniy",
            "cursedAssault",
            "bossGluhar",
            "followerGluharAssault",
            "followerGluharSecurity",
            "followerGluharScout",
            "followerGluharSnipe",
            "followerSanitar",
            "bossSanitar",
            "test",
            "assaultGroup",
            "sectantWarrior",
            "sectantPriest",
            "bossTagilla",
            "followerTagilla",
            "bossKnight",
            "followerBigPipe",
            "followerBirdEye",
            "bossBoar",
            "followerBoar",
            "arenaFighter",
            "arenaFighterEvent",
            "bossBoarSniper",
            "crazyAssaultEvent",
            "sectactPriestEvent",
            "followerBoarClose1",
            "followerBoarClose2",
            "bossKolontay",
            "followerKolontayAssault",
            "followerKolontaySecurity",
            "shooterBTR",
            "bossPartisan",
            "spiritWinter",
            "spiritSpring",
            "peacemaker",
            "skier",
            "assault",
            "marksman",
            "pmcUSEC",
            "pmcBEAR",
            "exUsec",
            "pmcBot",
            "bossBully",
        ],
        AlwaysFriends: [
            "bossZryachiy",
            "followerZryachiy",
            "peacefullZryachiyEvent",
            "ravangeZryachiyEvent",
            "gifter",
        ],
        BearEnemyChance: 100,
        BearPlayerBehaviour: "AlwaysEnemies",
        BotRole: "pmcBEAR",
        ChancedEnemies: [],
        Neutral: [],
        SavagePlayerBehaviour: "AlwaysEnemies",
        UsecEnemyChance: 100,
        UsecPlayerBehaviour: "AlwaysEnemies",
        Warn: ["sectactPriestEvent"],
    },
    {
        AlwaysEnemies: [
            "bossTest",
            "followerTest",
            "bossKilla",
            "bossKojaniy",
            "followerKojaniy",
            "cursedAssault",
            "bossGluhar",
            "followerGluharAssault",
            "followerGluharSecurity",
            "followerGluharScout",
            "followerGluharSnipe",
            "followerSanitar",
            "bossSanitar",
            "test",
            "assaultGroup",
            "sectantWarrior",
            "sectantPriest",
            "bossTagilla",
            "followerTagilla",
            "bossKnight",
            "followerBigPipe",
            "followerBirdEye",
            "bossBoar",
            "followerBoar",
            "arenaFighter",
            "arenaFighterEvent",
            "bossBoarSniper",
            "crazyAssaultEvent",
            "sectactPriestEvent",
            "followerBoarClose1",
            "followerBoarClose2",
            "bossKolontay",
            "followerKolontayAssault",
            "followerKolontaySecurity",
            "shooterBTR",
            "bossPartisan",
            "spiritWinter",
            "spiritSpring",
            "peacemaker",
            "skier",
            "assault",
            "marksman",
            "pmcUSEC",
            "pmcBEAR",
            "exUsec",
            "pmcBot",
            "bossBully",
        ],
        AlwaysFriends: [
            "bossZryachiy",
            "followerZryachiy",
            "peacefullZryachiyEvent",
            "ravangeZryachiyEvent",
            "gifter",
        ],
        BearEnemyChance: 100,
        BearPlayerBehaviour: "AlwaysEnemies",
        BotRole: "pmcUSEC",
        ChancedEnemies: [],
        Neutral: [],
        SavagePlayerBehaviour: "AlwaysEnemies",
        UsecEnemyChance: 100,
        UsecPlayerBehaviour: "AlwaysEnemies",
        Warn: ["sectactPriestEvent"],
    },
];
exports.configLocations = [
    "customs",
    "factoryDay",
    "factoryNight",
    "interchange",
    "laboratory",
    "lighthouse",
    "rezervbase",
    "shoreline",
    "tarkovstreets",
    "woods",
    "gzLow",
    "gzHigh",
];
exports.originalMapList = [
    "bigmap",
    "factory4_day",
    "factory4_night",
    "interchange",
    "laboratory",
    "lighthouse",
    "rezervbase",
    "shoreline",
    "tarkovstreets",
    "woods",
    "sandbox",
    "sandbox_high",
];
exports.bossesToRemoveFromPool = new Set([
    "assault",
    "pmcBEAR",
    "pmcUSEC",
    "infectedAssault",
    "infectedTagilla",
    "infectedLaborant",
    "infectedCivil",
]);
exports.mainBossNameList = [
    "bossKojaniy",
    "bossGluhar",
    "bossSanitar",
    "bossKilla",
    "bossTagilla",
    "bossKnight",
    "bossBoar",
    "bossKolontay",
    "bossPartisan",
    "bossBully",
];
exports.defaultEscapeTimes = {
    customs: 40,
    factoryDay: 20,
    factoryNight: 25,
    interchange: 40,
    laboratory: 35,
    lighthouse: 40,
    rezervbase: 40,
    shoreline: 45,
    tarkovstreets: 50,
    woods: 40,
    gzLow: 35,
    gzHigh: 35,
};
//# sourceMappingURL=constants.js.map